name: carg
description: Get coinched ! Mobile app to save your card games

version: 1.3.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^3.0.0
  firebase_crashlytics: ^2.0.2
  firebase_core: ^1.0.0
  firebase_auth: ^3.1.0
  firebase_auth_web: ^3.1.0
  firebase_dynamic_links: ^4.0.0
  google_sign_in: ^5.0.1
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  flutter_markdown: ^0.6.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^1.0.0
  flutter_secure_storage: ^5.0.0
  flutter_libphonenumber: ^1.1.0
  font_awesome_flutter: ^9.1.0
  http: ^0.13.0
  intl: ^0.17.0
  package_info_plus : ^1.4.0
  provider: ^6.0.0
  url_launcher: ^6.0.2
  syncfusion_flutter_charts: ^20.0.0
  syncfusion_flutter_gauges: ^19.1.54+1
  infinite_scroll_pagination: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pin_code_fields: ^7.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  network_image_mock: ^2.0.1
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true

  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Regular.ttf
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Bold.ttf

  assets:
    - assets/images/card_game.svg
    - assets/images/search_by_algolia.svg
    - assets/images/google_logo.svg
    - assets/config/
    - assets/rules/
    - CHANGELOG.md

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: assets/images/card_game_icon.png
  image_path_android: assets/images/card_game_icon.png

module:
  androidX: true
